//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attach
    {
        public int Id { get; set; }
        public string AFile { get; set; }
        public byte AType { get; set; }
        public int SAId { get; set; }
        public int AgentId { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
        public byte State { get; set; }
        public int SLogId { get; set; }
        public string UpLoadFile { get; set; }
        public int RemoveSLogId { get; set; }
    }
}
