//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanKaOrder
    {
        public int Id { get; set; }
        public int BKTId { get; set; }
        public int UId { get; set; }
        public string OId { get; set; }
        public decimal Amoney { get; set; }
        public int Agent { get; set; }
        public double AgentGet { get; set; }
        public byte AgentState { get; set; }
        public int AId { get; set; }
        public int FId { get; set; }
        public byte OrderState { get; set; }
        public byte PayState { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remark { get; set; }
        public byte IsDel { get; set; }
        public double AIdGet { get; set; }
    }
}
