//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string PasWd { get; set; }
        public Nullable<byte> LState { get; set; }
        public int AId { get; set; }
        public Nullable<byte> State { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public byte IsDel { get; set; }
        public int AdminId { get; set; }
        public Nullable<int> PUId { get; set; }
        public Nullable<System.DateTime> ActTime { get; set; }
        public byte Auto { get; set; }
    }
}
