//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckUser
    {
        public int Id { get; set; }
        public decimal PastMoney { get; set; }
        public decimal PastFrozen { get; set; }
        public decimal CheckMoney { get; set; }
        public decimal CheckFrozen { get; set; }
        public System.DateTime AddTime { get; set; }
        public decimal NowMoney { get; set; }
        public decimal NowFrozen { get; set; }
        public byte IsDel { get; set; }
        public System.DateTime TaskDate { get; set; }
        public int UId { get; set; }
        public string Remark { get; set; }
    }
}
