//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckResult
    {
        public int Id { get; set; }
        public string TNum { get; set; }
        public int CheckType { get; set; }
        public string CheckMsg { get; set; }
        public System.DateTime CheckTime { get; set; }
        public decimal Amount { get; set; }
        public byte IsDel { get; set; }
        public System.DateTime TaskDate { get; set; }
        public int UId { get; set; }
        public string Remark { get; set; }
    }
}
