//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutUsers
    {
        public int Id { get; set; }
        public Nullable<int> CAId { get; set; }
        public Nullable<int> WXId { get; set; }
        public string NickName { get; set; }
        public int Times { get; set; }
        public decimal AllPrice { get; set; }
        public decimal MyPrice { get; set; }
        public decimal CutPrice { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte State { get; set; }
        public byte IsDel { get; set; }
    }
}
