//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiLiApply
    {
        public int Id { get; set; }
        public string TureName { get; set; }
        public string Remark { get; set; }
        public decimal Amoney { get; set; }
        public int Agent { get; set; }
        public int AId { get; set; }
        public byte OrderState { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
        public string Mobile { get; set; }
        public string Area { get; set; }
        public string IdCard { get; set; }
        public string IdCardPlace { get; set; }
        public string IdCardPic { get; set; }
        public string Address { get; set; }
        public string YingYeName { get; set; }
        public string YingYeNum { get; set; }
        public string YingYePic { get; set; }
        public string SuiWuNum { get; set; }
        public string SuiWuPic { get; set; }
        public string ZuZhiNum { get; set; }
        public string ZuZhiPic { get; set; }
        public string BankPic { get; set; }
        public string Photo { get; set; }
        public string Pic1 { get; set; }
        public string Pic2 { get; set; }
        public string Pic3 { get; set; }
        public string Pic4 { get; set; }
    }
}
