//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Account_DailyStatistic
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Frozen { get; set; }
    }
}
