//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FastUserPay
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public int PayWay { get; set; }
        public string MerId { get; set; }
        public string MerKey { get; set; }
        public decimal UserCost { get; set; }
        public decimal UserCash { get; set; }
        public byte MerState { get; set; }
        public string MerMsg { get; set; }
        public byte CardState { get; set; }
        public string CardMsg { get; set; }
        public byte BusiState { get; set; }
        public string BusiMsg { get; set; }
        public string ArrayInfo { get; set; }
        public string CardName { get; set; }
        public string Bank { get; set; }
        public string Card { get; set; }
        public string Bin { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
        public decimal UserCost2 { get; set; }
        public decimal UserCost3 { get; set; }
    }
}
