//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FastPayWay
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public decimal BankCost { get; set; }
        public decimal BankCost2 { get; set; }
        public decimal Cash { get; set; }
        public string DllName { get; set; }
        public string GroupType { get; set; }
        public string Version { get; set; }
        public int Sort { get; set; }
        public string QueryArray { get; set; }
        public byte NeekReg { get; set; }
        public byte NeekCard { get; set; }
        public byte State { get; set; }
        public byte IsDel { get; set; }
        public byte HasWeiXin { get; set; }
        public byte HasAliPay { get; set; }
        public decimal SNum { get; set; }
        public decimal ENum { get; set; }
        public decimal SNum2 { get; set; }
        public decimal ENum2 { get; set; }
        public byte TimeType { get; set; }
        public System.DateTime STime { get; set; }
        public System.DateTime ETime { get; set; }
        public byte HasBank { get; set; }
        public decimal BankSNum { get; set; }
        public decimal BankENum { get; set; }
        public decimal BankCost3 { get; set; }
        public System.DateTime AddTime { get; set; }
        public string ShowName { get; set; }
        public byte CanOpenAliPay { get; set; }
        public byte CanOpenWeiXin { get; set; }
        public byte CanOpenBank { get; set; }
        public decimal MinCost { get; set; }
        public decimal MaxCost { get; set; }
        public decimal MinCost2 { get; set; }
        public decimal MaxCost2 { get; set; }
        public decimal MinCost3 { get; set; }
        public decimal MaxCost3 { get; set; }
        public decimal InCost { get; set; }
        public decimal InCost2 { get; set; }
        public decimal InCost3 { get; set; }
        public decimal Cost2 { get; set; }
        public decimal Cost3 { get; set; }
        public byte ManE { get; set; }
    }
}
