//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinTotal
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Update { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
        public Nullable<decimal> TotalAmoney { get; set; }
        public Nullable<decimal> TotlaPoundage { get; set; }
        public Nullable<decimal> Amoney1 { get; set; }
        public Nullable<decimal> Poundage1 { get; set; }
        public Nullable<decimal> Amoney2 { get; set; }
        public Nullable<decimal> Poundage2 { get; set; }
        public Nullable<decimal> Amoney2_0 { get; set; }
        public Nullable<decimal> Poundage2_0 { get; set; }
        public Nullable<int> Number2 { get; set; }
        public Nullable<decimal> Poundage2_1 { get; set; }
        public Nullable<decimal> Amoney3 { get; set; }
        public Nullable<decimal> Poundage3 { get; set; }
        public Nullable<decimal> Amoney4 { get; set; }
        public Nullable<decimal> Poundage4 { get; set; }
        public Nullable<decimal> Amoney5 { get; set; }
        public Nullable<decimal> Poundage5 { get; set; }
        public Nullable<decimal> Amoney5_0 { get; set; }
        public Nullable<decimal> Poundage5_0 { get; set; }
        public Nullable<decimal> Amoney6 { get; set; }
        public Nullable<decimal> Poundage6 { get; set; }
        public Nullable<decimal> Amoney7 { get; set; }
        public Nullable<decimal> Poundage7 { get; set; }
        public Nullable<decimal> Amoney8 { get; set; }
        public Nullable<decimal> Poundage8 { get; set; }
        public Nullable<decimal> Amoney9 { get; set; }
        public Nullable<decimal> Poundage9 { get; set; }
        public Nullable<decimal> Amoney10 { get; set; }
        public Nullable<decimal> Poundage10 { get; set; }
    }
}
