//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPayWay
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public decimal MinCost { get; set; }
        public decimal MaxCost { get; set; }
        public decimal CostAgent { get; set; }
        public decimal MinAgentCost { get; set; }
        public decimal MaxAgentCost { get; set; }
        public string DllName { get; set; }
        public string GroupType { get; set; }
        public string Version { get; set; }
        public int Sort { get; set; }
        public string QueryArray { get; set; }
        public byte State { get; set; }
        public byte IsDel { get; set; }
        public decimal SNum { get; set; }
        public decimal ENum { get; set; }
    }
}
