//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgCallBack
    {
        public int Id { get; set; }
        public Nullable<int> UId { get; set; }
        public string NeekName { get; set; }
        public string Linker { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string Result { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public Nullable<int> AId { get; set; }
        public byte IsDel { get; set; }
    }
}
