//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTemplate
    {
        public int Id { get; set; }
        public Nullable<byte> SendWay { get; set; }
        public string Tag { get; set; }
        public byte OrderType { get; set; }
        public byte OrderState { get; set; }
        public byte PayState { get; set; }
        public byte IdCardState { get; set; }
        public string Title { get; set; }
        public string Info { get; set; }
        public byte State { get; set; }
        public Nullable<byte> IsManage { get; set; }
        public string MLink { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
    }
}
