//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLog
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public string Mobile { get; set; }
        public string SendText { get; set; }
        public byte State { get; set; }
        public Nullable<System.DateTime> Timing { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string Code { get; set; }
        public string Result { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
    }
}
