//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAgent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Linker { get; set; }
        public string LinkMobile { get; set; }
        public Nullable<int> AdminId { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public double PayGet { get; set; }
        public double CashGet { get; set; }
        public byte IsDel { get; set; }
        public double LoanGet { get; set; }
        public double Credit { get; set; }
        public string ApkVer { get; set; }
        public Nullable<int> ApkInt { get; set; }
        public string ApkUrl { get; set; }
        public string ApkYYB { get; set; }
        public string ApkInfo { get; set; }
        public string IosVer { get; set; }
        public Nullable<int> IosInt { get; set; }
        public string IosUrl { get; set; }
        public string IosYYB { get; set; }
        public string IosInfo { get; set; }
        public byte IsTeiPai { get; set; }
        public string ShareIco { get; set; }
        public string CradBg { get; set; }
        public string ShareBg { get; set; }
        public string DownBg1 { get; set; }
        public string DownBg2 { get; set; }
        public string DownBg3 { get; set; }
        public double DaiLiGet { get; set; }
        public byte DaiLiGetType { get; set; }
        public int MyUId { get; set; }
        public string APPTag { get; set; }
        public int AgentID { get; set; }
        public byte IsPromote { get; set; }
        public double PromoteGet { get; set; }
        public byte Tier { get; set; }
        public byte Levels { get; set; }
        public int AgentTypeID { get; set; }
        public byte IsShowWord { get; set; }
        public string CompanyLogo { get; set; }
        public string Salesman { get; set; }
        public System.DateTime ExpireTime { get; set; }
        public decimal AgentFee { get; set; }
        public string MsgExt { get; set; }
        public string APPName { get; set; }
        public string NoteDownload { get; set; }
        public byte APPHasMore { get; set; }
        public int AppBtnNumber { get; set; }
        public int AppMenuHome { get; set; }
        public int AppMenuMore { get; set; }
        public int AppMenuBottom { get; set; }
        public string ApkColor { get; set; }
        public string IosColor { get; set; }
        public Nullable<int> AgentState { get; set; }
        public string AgentRegion { get; set; }
        public decimal ECash0 { get; set; }
        public decimal Cash0 { get; set; }
        public decimal ECash1 { get; set; }
        public decimal Cash1 { get; set; }
        public int Cash0Times { get; set; }
        public int Cash1Times { get; set; }
        public byte Set3 { get; set; }
        public byte MaxTier { get; set; }
        public byte Set4 { get; set; }
        public byte AgentLevelMax { get; set; }
        public string Agreement { get; set; }
        public int SameAgent { get; set; }
    }
}
