//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLog
    {
        public long Id { get; set; }
        public Nullable<byte> MLType { get; set; }
        public int AId { get; set; }
        public string TrueName { get; set; }
        public string Title { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RQData { get; set; }
        public string POSTData { get; set; }
        public string IP { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
        public byte PType { get; set; }
    }
}
