//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMoneySet
    {
        public int Id { get; set; }
        public byte IsDel { get; set; }
        public decimal PaySplitA1 { get; set; }
        public decimal PaySplitA2 { get; set; }
        public decimal PaySplitA3 { get; set; }
        public decimal PaySplitA4 { get; set; }
        public decimal PaySplitA5 { get; set; }
        public decimal PaySplitA6 { get; set; }
        public decimal PaySplitU0 { get; set; }
        public decimal PaySplitU1 { get; set; }
        public decimal PaySplitU2 { get; set; }
        public decimal VipPrice { get; set; }
        public decimal VipSplitA1 { get; set; }
        public decimal VipSplitA2 { get; set; }
        public decimal VipSplitA3 { get; set; }
        public decimal VipSplitA4 { get; set; }
        public decimal VipSplitA5 { get; set; }
        public decimal VipSplitA6 { get; set; }
        public decimal VipSplitU0 { get; set; }
        public decimal VipSplitU1 { get; set; }
        public decimal VipSplitU2 { get; set; }
        public decimal AgentPrice1 { get; set; }
        public decimal AgentPrice2 { get; set; }
        public decimal AgentPrice3 { get; set; }
        public decimal AgentPrice4 { get; set; }
        public decimal AgentPrice5 { get; set; }
        public decimal AgentPrice6 { get; set; }
        public decimal AgentSplit0 { get; set; }
        public decimal AgentSplit1 { get; set; }
        public decimal AgentSplit2 { get; set; }
        public decimal AgentSplit3 { get; set; }
        public decimal AgentSplit4 { get; set; }
        public decimal AgentSplit5 { get; set; }
        public decimal SameAgent { get; set; }
    }
}
