//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysSet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AgentName { get; set; }
        public string ICP { get; set; }
        public string Tel { get; set; }
        public string Agreement { get; set; }
        public double House { get; set; }
        public byte CashChecked { get; set; }
        public byte CashPayWay { get; set; }
        public decimal Cash0 { get; set; }
        public decimal ECash0 { get; set; }
        public decimal QCash0 { get; set; }
        public decimal Cash1 { get; set; }
        public decimal ECash1 { get; set; }
        public Nullable<int> CashDay { get; set; }
        public Nullable<int> CashNum { get; set; }
        public Nullable<decimal> CashMoney { get; set; }
        public byte IsDel { get; set; }
        public string ApkVer { get; set; }
        public Nullable<int> ApkInt { get; set; }
        public string ApkUrl { get; set; }
        public string ApkYYB { get; set; }
        public string ApkInfo { get; set; }
        public string IosVer { get; set; }
        public Nullable<int> IosInt { get; set; }
        public string IosUrl { get; set; }
        public string IosYYB { get; set; }
        public string IosInfo { get; set; }
        public int SMSTimes { get; set; }
        public int SMSActives { get; set; }
        public string SMSEnd { get; set; }
        public int LoginLock { get; set; }
        public int PayLock { get; set; }
        public Nullable<byte> APKState { get; set; }
        public Nullable<byte> IOSState { get; set; }
        public decimal CtrlMoney1 { get; set; }
        public byte ApkSet1 { get; set; }
        public byte IosSet1 { get; set; }
        public byte ApkSet2 { get; set; }
        public byte IosSet2 { get; set; }
        public byte ApkSet3 { get; set; }
        public byte IosSet3 { get; set; }
        public byte ApkSet4 { get; set; }
        public byte IosSet4 { get; set; }
        public byte ApkSet5 { get; set; }
        public byte IosSet5 { get; set; }
        public byte ApkSet6 { get; set; }
        public byte IosSet6 { get; set; }
        public byte ApkSet7 { get; set; }
        public byte IosSet7 { get; set; }
        public byte ApkSet8 { get; set; }
        public byte IosSet8 { get; set; }
        public byte ApkSet9 { get; set; }
        public byte IosSet9 { get; set; }
        public byte ApkSet10 { get; set; }
        public byte IosSet10 { get; set; }
        public byte ApkSet11 { get; set; }
        public byte IosSet11 { get; set; }
        public byte ApkSet12 { get; set; }
        public byte IosSet12 { get; set; }
        public byte ApkSet13 { get; set; }
        public byte IosSet13 { get; set; }
        public byte ApkSet14 { get; set; }
        public byte IosSet14 { get; set; }
        public byte ApkSet15 { get; set; }
        public byte IosSet15 { get; set; }
        public decimal Level1Price { get; set; }
        public decimal Level2Price { get; set; }
        public decimal Level3Price { get; set; }
        public decimal Level4Price { get; set; }
        public decimal Level5Price { get; set; }
        public byte AutoPay { get; set; }
        public byte GlobalAgentMaxLevel { get; set; }
        public byte GlobaPromoteMaxLevel { get; set; }
        public int AppMenuHome { get; set; }
        public int AppMenuMore { get; set; }
        public int AppMenuBottom { get; set; }
        public string AppWord { get; set; }
        public string SW1Key { get; set; }
        public string SW1KeyT { get; set; }
        public Nullable<System.DateTime> SW1sTime { get; set; }
        public Nullable<System.DateTime> SW1eTime { get; set; }
        public string SW2Key { get; set; }
        public string SW2KeyT { get; set; }
        public Nullable<System.DateTime> SW2sTime { get; set; }
        public Nullable<System.DateTime> SW2eTime { get; set; }
        public int AppBtnNumber { get; set; }
        public string ApkColor { get; set; }
        public string IosColor { get; set; }
        public byte APPHasMore { get; set; }
        public byte LagEntry { get; set; }
        public byte LagEntryNum { get; set; }
        public byte LagEntryDay { get; set; }
        public decimal AgentGet { get; set; }
        public int Cash0Times { get; set; }
        public int Cash1Times { get; set; }
        public decimal PayConfigAgent { get; set; }
        public decimal AutoCashMoney { get; set; }
        public string NoWord { get; set; }
        public decimal SysECash0 { get; set; }
        public decimal SysCash0 { get; set; }
        public decimal SysECash1 { get; set; }
        public decimal SysCash1 { get; set; }
        public decimal AgentECash0 { get; set; }
        public decimal AgentCash0 { get; set; }
        public decimal AgentECash1 { get; set; }
        public decimal AgentCash1 { get; set; }
        public int AgentCash0Times { get; set; }
        public int AgentCash1Times { get; set; }
        public byte AuthType { get; set; }
        public decimal AuthPrice { get; set; }
        public byte ShanHuZiXuan { get; set; }
        public byte ShouYinTai { get; set; }
        public byte ZhiTongChe { get; set; }
        public string CashAlertMsgT0 { get; set; }
        public string CashAlertMsgT1 { get; set; }
        public byte GetOrderWay { get; set; }
        public byte ApkAutoUpdate { get; set; }
        public byte IosAutoUpdate { get; set; }
        public int YaoQingIntervalTime { get; set; }
        public int YaoQingIntervalNumber { get; set; }
        public string BaoUserAlert { get; set; }
        public decimal EveryDayMaxCash { get; set; }
        public int AuthMinAge { get; set; }
        public int AuthMaxAge { get; set; }
        public byte AgentWay { get; set; }
        public byte OpenAutoAuthAndroid { get; set; }
        public string AutoAuthAppKeyAndroid { get; set; }
        public string AutoAuthAppSecretAndroid { get; set; }
        public string AutoAuthAppCodeAndroid { get; set; }
        public byte OpenAutoAuthIOS { get; set; }
        public string AutoAuthAppKeyIOS { get; set; }
        public string AutoAuthAppSecretIOS { get; set; }
        public string AutoAuthAppCodeIOS { get; set; }
    }
}
