//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCashInfo
    {
        public int Id { get; set; }
        public string OId { get; set; }
        public Nullable<int> TId { get; set; }
        public byte State { get; set; }
        public byte OState { get; set; }
        public byte NState { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remark { get; set; }
        public byte IsDel { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<System.DateTime> ETime { get; set; }
    }
}
