//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersFace
    {
        public int Id { get; set; }
        public Nullable<int> UId { get; set; }
        public byte CType { get; set; }
        public string TrueName { get; set; }
        public string Mobile { get; set; }
        public byte CardStae { get; set; }
        public string RegAddress { get; set; }
        public int Agent { get; set; }
        public int AId { get; set; }
        public byte IsDaiLi { get; set; }
        public byte MobileType { get; set; }
        public int Times { get; set; }
        public string When { get; set; }
        public string Remark { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public byte IsNew { get; set; }
    }
}
