//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuth
    {
        public int Id { get; set; }
        public Nullable<int> UId { get; set; }
        public string OId { get; set; }
        public string BankAccount { get; set; }
        public string AccountName { get; set; }
        public string IdentityCode { get; set; }
        public string Mobile { get; set; }
        public string CVV { get; set; }
        public string EndDate { get; set; }
        public string RetCode { get; set; }
        public string RetMsg { get; set; }
        public string RetLog { get; set; }
        public byte IsCharge { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
        public byte AuthType { get; set; }
        public decimal AuthPrice { get; set; }
    }
}
