//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string NeekName { get; set; }
        public string TrueName { get; set; }
        public string Mobile { get; set; }
        public byte MobileState { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public byte EmailState { get; set; }
        public string Address { get; set; }
        public string CardId { get; set; }
        public string CardPic { get; set; }
        public byte CardStae { get; set; }
        public byte State { get; set; }
        public decimal Amount { get; set; }
        public decimal Frozen { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsDel { get; set; }
        public string RegAddress { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string PayPwd { get; set; }
        public byte MiBao { get; set; }
        public string CardNum { get; set; }
        public int Agent { get; set; }
        public int AId { get; set; }
        public string Token { get; set; }
        public string Pic { get; set; }
        public string CardImg1 { get; set; }
        public string CardImg2 { get; set; }
        public string CardFace { get; set; }
        public string CardBack { get; set; }
        public string CardRemark { get; set; }
        public int LoginErr { get; set; }
        public int LoginLock { get; set; }
        public int PayErr { get; set; }
        public int PayLock { get; set; }
        public Nullable<int> MyPId { get; set; }
        public string ENo { get; set; }
        public int PayConfigId { get; set; }
        public byte CardType { get; set; }
        public int SAId { get; set; }
        public byte SALevel { get; set; }
        public string ShopInfo { get; set; }
        public string ShopTel { get; set; }
        public string ShopNotice { get; set; }
        public string Remark { get; set; }
        public Nullable<byte> ShareType { get; set; }
        public decimal Cash0 { get; set; }
        public decimal ECash0 { get; set; }
        public decimal Cash1 { get; set; }
        public decimal ECash1 { get; set; }
        public byte StopPayState { get; set; }
        public string StopPayRemark { get; set; }
        public decimal StopPayMoney { get; set; }
        public decimal CashFastPer { get; set; }
        public decimal CashFastMax { get; set; }
        public decimal TodayMoney { get; set; }
        public byte YYOpenState { get; set; }
        public byte InTypeMobile { get; set; }
        public byte InTypePC { get; set; }
        public string AssureImgName { get; set; }
        public byte HasT0 { get; set; }
        public int T0Times { get; set; }
        public int T1Times { get; set; }
        public string PrintToken { get; set; }
        public Nullable<System.DateTime> AddAuthTime { get; set; }
        public byte AutoBao { get; set; }
        public byte AutoCash { get; set; }
        public decimal AutoCashMoney { get; set; }
        public Nullable<int> AutoCashBank { get; set; }
        public byte StopPayAuditState { get; set; }
        public string CarLicensePic { get; set; }
        public string CarLocationPic { get; set; }
        public string CarOther { get; set; }
        public decimal YAmount { get; set; }
        public decimal AllRec { get; set; }
        public decimal LastRec { get; set; }
        public byte IfCanIn { get; set; }
        public string CardTrueName { get; set; }
        public string CardGender { get; set; }
        public string CardNation { get; set; }
        public string CardAddress { get; set; }
        public string CardIssue { get; set; }
        public Nullable<System.DateTime> CardValidSDate { get; set; }
        public Nullable<System.DateTime> CardValidEDate { get; set; }
        public Nullable<decimal> Sp_Amount { get; set; }
        public byte CardBackMode { get; set; }
        public byte CardFrontMode { get; set; }
        public byte IsVip { get; set; }
        public Nullable<System.DateTime> VipETime { get; set; }
    }
}
