//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKLMModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YYDaily
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public string DevId { get; set; }
        public System.DateTime OutDate { get; set; }
        public string PageId { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte State { get; set; }
        public byte IsDel { get; set; }
        public int ClickPV { get; set; }
        public int ClickUV { get; set; }
        public int ShakePV { get; set; }
        public int ShakeUV { get; set; }
    }
}
