//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int AgentID { get; set; }
        public decimal RegisterFee { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public double RegisterPayGet { get; set; }
    }
}
