//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPModule
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PicUrl { get; set; }
        public string PictureUrl { get; set; }
        public string Value { get; set; }
        public byte ModuleType { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte State { get; set; }
        public byte DisplaySite { get; set; }
        public int Sort { get; set; }
        public int AgentId { get; set; }
        public bool IsLock { get; set; }
        public int Version { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
    }
}
