//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUpdate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string ApkVer { get; set; }
        public Nullable<int> ApkInt { get; set; }
        public string ApkUrl { get; set; }
        public string ApkYYB { get; set; }
        public string ApkInfo { get; set; }
        public string ApkColor { get; set; }
        public byte APKState { get; set; }
        public string IosVer { get; set; }
        public Nullable<int> IosInt { get; set; }
        public string IosUrl { get; set; }
        public string IosYYB { get; set; }
        public string IosInfo { get; set; }
        public byte IOSState { get; set; }
        public string IosColor { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
