//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attach
    {
        public int Id { get; set; }
        public string AFile { get; set; }
        public byte AType { get; set; }
        public int SAId { get; set; }
        public int AgentId { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte State { get; set; }
        public int SLogId { get; set; }
        public string UpLoadFile { get; set; }
        public int RemoveSLogId { get; set; }
    }
}
