//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanKaOrder
    {
        public int Id { get; set; }
        public int BKTId { get; set; }
        public int UId { get; set; }
        public string OId { get; set; }
        public decimal Amoney { get; set; }
        public int Agent { get; set; }
        public double AgentGet { get; set; }
        public byte AgentState { get; set; }
        public int AId { get; set; }
        public int FId { get; set; }
        public byte OrderState { get; set; }
        public byte PayState { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remark { get; set; }
        public double AIdGet { get; set; }
    }
}
