//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicDesc
    {
        public int Id { get; set; }
        public string CharCode { get; set; }
        public string TitleCode { get; set; }
        public string DescText { get; set; }
        public int Sort { get; set; }
    }
}
