//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicBank
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public byte State { get; set; }
        public string Code { get; set; }
        public byte IsApply { get; set; }
        public string Actives { get; set; }
        public string Info { get; set; }
        public byte IsJieJi { get; set; }
        public byte IsDaiJi { get; set; }
        public byte IsPayCard { get; set; }
        public string Logo1 { get; set; }
        public string Logo2 { get; set; }
        public string Logo3 { get; set; }
        public string CreditCardUrl { get; set; }
        public string BIN { get; set; }
        public byte CanCredit { get; set; }
    }
}
