//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string PasWd { get; set; }
        public Nullable<byte> LState { get; set; }
        public int AId { get; set; }
        public Nullable<byte> State { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public int AdminId { get; set; }
        public Nullable<int> PUId { get; set; }
        public Nullable<System.DateTime> ActTime { get; set; }
        public byte Auto { get; set; }
    }
}
