//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckUserMoney
    {
        public int Id { get; set; }
        public int Progress { get; set; }
        public decimal ChangeMoney { get; set; }
        public decimal ChangeFrozen { get; set; }
        public decimal ProgressMoney { get; set; }
        public decimal RecordMoney { get; set; }
        public System.DateTime TaskDate { get; set; }
        public int UId { get; set; }
    }
}
