//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckResult
    {
        public int Id { get; set; }
        public string TNum { get; set; }
        public int CheckType { get; set; }
        public string CheckMsg { get; set; }
        public System.DateTime CheckTime { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TaskDate { get; set; }
        public int UId { get; set; }
        public string Remark { get; set; }
    }
}
