//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutLog
    {
        public int Id { get; set; }
        public int CAId { get; set; }
        public decimal Amoney { get; set; }
        public System.DateTime AddTime { get; set; }
        public int CUId { get; set; }
        public int CUIded { get; set; }
        public string NickName { get; set; }
        public string NickNamed { get; set; }
    }
}
