//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Account_DailyCompared
    {
        public int Id { get; set; }
        public Nullable<decimal> ORDERS_1 { get; set; }
        public Nullable<decimal> ORDERS_P1 { get; set; }
        public Nullable<decimal> ORDERS_7 { get; set; }
        public Nullable<decimal> ORDERS_P7 { get; set; }
        public Nullable<decimal> ORDERS_8 { get; set; }
        public Nullable<decimal> ORDERS_P8 { get; set; }
        public Nullable<decimal> ORDERS_9 { get; set; }
        public Nullable<decimal> ORDERS_P9 { get; set; }
        public Nullable<decimal> Baglog { get; set; }
        public Nullable<decimal> TurnLog { get; set; }
        public Nullable<decimal> OrderProfitLog { get; set; }
        public Nullable<decimal> ORDERS_3 { get; set; }
        public Nullable<decimal> ORDERS_P3 { get; set; }
        public Nullable<decimal> Userlog15 { get; set; }
        public Nullable<decimal> ORDERS_2 { get; set; }
        public Nullable<decimal> ORDERS_5 { get; set; }
        public Nullable<decimal> ORDERS_6 { get; set; }
        public Nullable<decimal> ORDERS_12 { get; set; }
        public Nullable<decimal> UserAuth { get; set; }
        public Nullable<decimal> U_Amony { get; set; }
        public Nullable<decimal> U_Frozen { get; set; }
        public Nullable<decimal> B_Amony { get; set; }
        public Nullable<decimal> DiffResult { get; set; }
        public Nullable<System.DateTime> DATED { get; set; }
    }
}
