//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FastOrder
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public string TNum { get; set; }
        public string Trade { get; set; }
        public string PayId { get; set; }
        public byte OType { get; set; }
        public decimal Amoney { get; set; }
        public decimal PayMoney { get; set; }
        public decimal Poundage { get; set; }
        public decimal UserRate { get; set; }
        public decimal AgentRate { get; set; }
        public decimal SysRate { get; set; }
        public decimal SysCash { get; set; }
        public decimal UserCash { get; set; }
        public decimal AgentPayGet { get; set; }
        public int Agent { get; set; }
        public string AgentPath { get; set; }
        public string Split { get; set; }
        public decimal HFGet { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<int> PayWay { get; set; }
        public byte PayState { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public byte AgentState { get; set; }
        public Nullable<System.DateTime> AgentTime { get; set; }
        public string Remark { get; set; }
        public byte UserState { get; set; }
        public Nullable<System.DateTime> UserTime { get; set; }
        public string CardName { get; set; }
        public string Bank { get; set; }
        public string Card { get; set; }
        public string Bin { get; set; }
        public byte ComeWay { get; set; }
        public byte AgentWay { get; set; }
        public string CashType { get; set; }
        public decimal SameGet { get; set; }
    }
}
