//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FastSplit
    {
        public int Id { get; set; }
        public string Tnum { get; set; }
        public decimal Profit { get; set; }
        public int AgentId { get; set; }
        public byte Tier { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
