//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrders
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public string TNum { get; set; }
        public decimal TotalMoney { get; set; }
        public decimal Amount { get; set; }
        public decimal Poundage { get; set; }
        public decimal HFGet { get; set; }
        public decimal AgentGet { get; set; }
        public decimal PayPoundage { get; set; }
        public decimal CashPoundage { get; set; }
        public decimal PayGet { get; set; }
        public decimal CashGet { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte PayState { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public int PayWay { get; set; }
        public byte PayedState { get; set; }
        public Nullable<System.DateTime> PayedTime { get; set; }
        public int CashWay { get; set; }
        public decimal PayRate { get; set; }
        public decimal PayMin { get; set; }
        public decimal PayMax { get; set; }
        public decimal CashRate { get; set; }
        public decimal CashMin { get; set; }
        public decimal CashMax { get; set; }
        public decimal UPayRate { get; set; }
        public decimal UPayMin { get; set; }
        public decimal UPayMax { get; set; }
        public decimal UCashRate { get; set; }
        public decimal UCashMin { get; set; }
        public decimal UCashMax { get; set; }
        public int AgentId { get; set; }
        public byte AgentState { get; set; }
        public Nullable<System.DateTime> AgentTime { get; set; }
        public int UserCardId { get; set; }
        public byte AdvCost { get; set; }
        public byte AdvCash { get; set; }
        public string Remark { get; set; }
        public string RemarkSplit { get; set; }
        public decimal SameGet { get; set; }
    }
}
