//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobUserPay
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public int PayWay { get; set; }
        public string MerId { get; set; }
        public string MerKey { get; set; }
        public string ArrayInfo { get; set; }
        public byte MerState { get; set; }
        public string MerMsg { get; set; }
        public byte CardState { get; set; }
        public string CardMsg { get; set; }
        public Nullable<byte> BusiState { get; set; }
        public string BusiMsg { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
