//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgNotice
    {
        public int Id { get; set; }
        public byte NType { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public byte Level { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public string ReadUsers { get; set; }
        public string ReadAdmin { get; set; }
        public int AgentId { get; set; }
        public byte IsPush { get; set; }
    }
}
