//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersDDLog
    {
        public int Id { get; set; }
        public string TNum { get; set; }
        public byte LogType { get; set; }
        public string Remark { get; set; }
        public string Img { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public string OpName { get; set; }
        public System.DateTime AddTime { get; set; }
        public string InteriorRemark { get; set; }
    }
}
