//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransfer
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public string OId { get; set; }
        public int RUId { get; set; }
        public decimal PayMoney { get; set; }
        public decimal Poundage { get; set; }
        public decimal Amoney { get; set; }
        public double SysRate { get; set; }
        public double UserRate { get; set; }
        public double AgentPayGet { get; set; }
        public string Remark { get; set; }
        public int Agent { get; set; }
        public int AId { get; set; }
        public int FId { get; set; }
        public byte OrderState { get; set; }
        public byte PayState { get; set; }
        public byte AgentState { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte IsMe { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<byte> PayWay { get; set; }
        public byte PayType { get; set; }
        public double AIdPayGet { get; set; }
    }
}
