//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProfitLog
    {
        public int Id { get; set; }
        public System.DateTime AddTime { get; set; }
        public int UId { get; set; }
        public string TNum { get; set; }
        public byte LogType { get; set; }
        public byte Tier { get; set; }
        public decimal Profit { get; set; }
        public string UserName { get; set; }
        public byte OrderType { get; set; }
        public decimal Amoney { get; set; }
        public int Agent { get; set; }
    }
}
