//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string TNum { get; set; }
        public int UId { get; set; }
        public string TName { get; set; }
        public int RUId { get; set; }
        public string RName { get; set; }
        public byte TType { get; set; }
        public byte TState { get; set; }
        public decimal Amoney { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte PayState { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public int PayWay { get; set; }
        public Nullable<System.DateTime> TrunTime { get; set; }
        public int Agent { get; set; }
        public byte AgentState { get; set; }
        public Nullable<System.DateTime> AgentTime { get; set; }
        public string Remark { get; set; }
        public string OrderAddress { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public int AId { get; set; }
        public int FId { get; set; }
        public Nullable<byte> TrunType { get; set; }
        public string UserCardPic { get; set; }
        public string UserCardId { get; set; }
        public string BankCardId { get; set; }
        public byte IdCardState { get; set; }
        public Nullable<System.DateTime> CardAddTime { get; set; }
        public Nullable<System.DateTime> CardEditTime { get; set; }
        public byte PayType { get; set; }
        public string PayName { get; set; }
        public byte CardUpType { get; set; }
        public decimal Poundage { get; set; }
        public byte DDAuto { get; set; }
        public string DDUserRm { get; set; }
        public Nullable<System.DateTime> DDLastTime { get; set; }
        public byte TDState { get; set; }
        public string InternalRm { get; set; }
        public decimal AgentPayGet { get; set; }
        public byte InState { get; set; }
        public Nullable<System.DateTime> InTimed { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public byte LagEntryNum { get; set; }
        public byte LagEntryDay { get; set; }
        public byte FrozenState { get; set; }
        public byte RepairState { get; set; }
        public Nullable<System.DateTime> CardUpdateTime { get; set; }
        public string DDAuditRemark { get; set; }
        public byte ComeWay { get; set; }
        public string UserCardName { get; set; }
        public byte RunSplit { get; set; }
    }
}
