//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayConfigChange
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Cash0 { get; set; }
        public decimal ECash0 { get; set; }
        public decimal Cash1 { get; set; }
        public decimal ECash1 { get; set; }
        public string Remark { get; set; }
        public Nullable<byte> State { get; set; }
        public Nullable<decimal> APrice { get; set; }
        public Nullable<decimal> BPrice { get; set; }
        public Nullable<decimal> CPrice { get; set; }
        public byte CState { get; set; }
        public byte EState { get; set; }
        public int ShareNumber { get; set; }
        public string ShowTip { get; set; }
        public string SubTitle { get; set; }
        public Nullable<int> AgentId { get; set; }
    }
}
