//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysControl
    {
        public int Id { get; set; }
        public string Tag { get; set; }
        public string CName { get; set; }
        public byte State { get; set; }
        public System.DateTime STime { get; set; }
        public System.DateTime ETime { get; set; }
        public byte TimeType { get; set; }
        public int SNum { get; set; }
        public int ENum { get; set; }
        public System.DateTime AddTime { get; set; }
        public int Sort { get; set; }
        public int PayWay { get; set; }
        public byte IsPay { get; set; }
        public byte LagEntryNum { get; set; }
        public byte LagEntryDay { get; set; }
    }
}
