//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLog
    {
        public long Id { get; set; }
        public Nullable<byte> MLType { get; set; }
        public int AId { get; set; }
        public string TrueName { get; set; }
        public string Title { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string RQData { get; set; }
        public string POSTData { get; set; }
        public string IP { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte PType { get; set; }
    }
}
