//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCash
    {
        public int Id { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public Nullable<System.DateTime> ETime { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Fail { get; set; }
    }
}
