//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turntable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PInfo { get; set; }
        public string PTips { get; set; }
        public System.DateTime STime { get; set; }
        public System.DateTime ETime { get; set; }
        public string ETips { get; set; }
        public string ETitle { get; set; }
        public string EInfo { get; set; }
        public int BaseNum { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte State { get; set; }
    }
}
