//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginSceneid
    {
        public int Id { get; set; }
        public Nullable<int> UId { get; set; }
        public string Token { get; set; }
        public int Times { get; set; }
        public string Sceneid { get; set; }
        public string Pic { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
