//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersFace
    {
        public int Id { get; set; }
        public Nullable<int> UId { get; set; }
        public byte CType { get; set; }
        public string TrueName { get; set; }
        public string Mobile { get; set; }
        public byte CardStae { get; set; }
        public string RegAddress { get; set; }
        public int Agent { get; set; }
        public int AId { get; set; }
        public byte IsDaiLi { get; set; }
        public byte MobileType { get; set; }
        public int Times { get; set; }
        public string When { get; set; }
        public string Remark { get; set; }
        public byte State { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public byte IsNew { get; set; }
    }
}
