//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCardOpen
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public string CardNum { get; set; }
        public string Mobile { get; set; }
        public string Token { get; set; }
        public System.DateTime STime { get; set; }
        public System.DateTime ETime { get; set; }
        public int PayWay { get; set; }
        public byte State { get; set; }
        public string RqData { get; set; }
    }
}
