//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPayChange
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public int SId { get; set; }
        public int SAId { get; set; }
        public string Pic { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remark { get; set; }
        public int AId { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string EditRemark { get; set; }
        public Nullable<byte> State { get; set; }
        public decimal Cash0 { get; set; }
        public decimal ECash0 { get; set; }
        public decimal CashNew0 { get; set; }
        public decimal ECashNew0 { get; set; }
        public decimal Cash1 { get; set; }
        public decimal ECash1 { get; set; }
        public decimal CashNew1 { get; set; }
        public decimal ECashNew1 { get; set; }
        public string ShowTip { get; set; }
        public string SubTitle { get; set; }
    }
}
