//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTrack
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public string UserName { get; set; }
        public string ENo { get; set; }
        public string OPType { get; set; }
        public string IP { get; set; }
        public string IPAddress { get; set; }
        public string EqMobile { get; set; }
        public string MobileAddress { get; set; }
        public string IfYY { get; set; }
        public string MobiType { get; set; }
        public string MobiSysType { get; set; }
        public string SysVer { get; set; }
        public string SoftVer { get; set; }
        public string SignalType { get; set; }
        public string GPSAddress { get; set; }
        public string GPSX { get; set; }
        public string GPSY { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
