//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LokFu.Repositories.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class YYApply
    {
        public int Id { get; set; }
        public string ApplyId { get; set; }
        public int Num { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Poi_Id { get; set; }
        public System.DateTime AddTime { get; set; }
        public byte State { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
    }
}
